"""
hexacolors
~~~~~~~~~~~~~~~~~~~

A simple library that converts string to hexadecimal understandable by python

:(c) 2022-present Marciel404
:license: MIT, see LICENSE for more details.
"""

__title__ = "Hexacolors"
__author__ = "Marciel404"
__license__ = "MIT"
__copyright__ = "2022-present Marciel404"
__version__ = "0.3.1"

__path__ = __import__("pkgutil").extend_path(__path__, __name__)

from .convertingcolor import hexacolor, stringcolor

listcolors = \
[
'Black',
'Gray1',
'Gray2',
'Gray3',
'DimGray',
'Gray',
'DarkGray',
'Silver',
'LightGrey',
'Gainsboro',
'SlateBlue',
'SlateBlue1',
'SlateBlue2',
'DarkSlateBlue',
'MidnightBlue',
'Navy',
'DarkBlue',
'MediumBlue',
'Blue',
'CornflowerBlue',
'RoyalBlue',
'DodgerBlue',
'DeepSkyBlue',
'LightSkyBlue',
'SkyBlue',
'LightBlue',
'SteelBlue',
'LightSteelBlue',
'SlateGray',
'LightSlateGray',
'Cyan',
'DarkTurquoise',
'Turquoise',
'MediumTurquoise',
'LightSeaGreen',
'DarkCyan',
'Teal',
'Aquamarine',
'MediumAquamarine',
'CadetBlue',
'DarkKhaki',
'Goldenrod',
'DarkGoldenrod',
'SaddleBrown',
'Sienna',
'RosyBrown',
'Peru',
'Chocolate',
'SandyBrown',
'NavajoWhite',
'Wheat',
'BurlyWood',
'Tan',
'MediumSlateBlue',
'MediumPurple',
'BlueViolet',
'Indigo',
'DarkViolet',
'DarkOrchid',
'MediumOrchid',
'Purple',
'DarkMagenta',
'Magenta',
'Violet',
'Orchid',
'Plum',
'MediumVioletRed',
'DeepPink',
'HotPink',
'PaleVioletRed',
'LightPink',
'Pink',
'LightCoral',
'IndianRed',
'Crimson',
'DarkSlateGray',
'MediumSpringGreen',
'SpringGreen',
'PaleGreen',
'LightGreen',
'DarkSeaGreen',
'MediumSeaGreen',
'SeaGreen',
'DarkGreen',
'Green',
'ForestGreen',
'LimeGreen',
'Lime',
'LawnGreen',
'Chartreuse',
'GreenYellow',
'YellowGreen',
'OliveDrab',
'DarkOliveGreen',
'Olive',
'Maroon',
'DarkRed',
'FireBrick',
'Brown',
'Salmon',
'DarkSalmon',
'LightSalmon',
'Coral',
'Tomato',
'Red',
'OrangeRed',
'DarkOrange',
'Orange',
'Gold',
'Yellow',
'Khaki',
]