from .gray import *
from .blue import *
from .cyan import *
from .brown import *
from .purple import *
from .pink import *
from .green import *
from .red import *
from .orange import *
from .yellow import *
from .ligthcolors import *