listblack =[
    'Black',
    'Grey1',
    'Grey2',
    'Grey3',
    'DimGray',
    'Gray',
    'DarkGray',
    'Silver',
    'LightGrey',
    'Gainsboro',
    'SlateGray',
    'LightSlateGray',
]

listblue =[
    'SlateBlue',
    'SlateBlue1',
    'SlateBlue2',
    'DarkSlateBlue',
    'MidnightBlue',
    'Navy',
    'DarkBlue',
    'MediumBlue',
    'Blue',
    'CornflowerBlue',
    'RoyalBlue',
    'DodgerBlue',
    'DeepSkyBlue',
    'LightSkyBlue',
    'SkyBlue',
    'LightBlue',
    'SteelBlue',
    'LightSteelBlue',
    'MediumSlateBlue',
]

listcyan =[
    'Cyan',
    'DarkTurquoise',
    'Turquoise',
    'MediumTurquoise',
    'LightSeaGreen',
    'DarkCyan',
    'Teal',
    'Aquamarine',
    'MediumAquamarine',
    'CadetBlue',
]

listgreen = [
    'DarkSlateGreen',
    'MediumSpringGreen',
    'SpringGreen',
    'PaleGreen',
    'LightGreen',
    'DarkSeaGreen',
    'MediumSeaGreen',
    'SeaGreen',
    'DarkGreen',
    'Green',
    'ForestGreen',
    'LimeGreen',
    'Lime',
    'LawnGreen',
    'Chartreuse',
    'GreenYellow',
    'YellowGreen',
    'OliveDrab',
    'DarkOliveGreen',
    'Olive',
]

listbrown =[
    'DarkKhaki',
    'Goldenrod',
    'DarkGoldenrod',
    'SaddleBrown',
    'Sienna',
    'RosyBrown',
    'Peru',
    'Chocolate',
    'SandyBrown',
    'NavajoWhite',
    'Wheat',
    'BurlyWood',
    'Tan',
]

listpurple =[
    'MediumPurple',
    'BlueViolet',
    'Indigo',
    'DarkViolet',
    'DarkOrchid',
    'MediumOrchid',
    'Purple',
    'DarkMagenta',
    'Magenta',
    'Violet',
    'Orchid',
    'Plum',
]

listpink =[
    'MediumVioletRed',
    'DeepPink',
    'HotPink',
    'PaleVioletRed',
    'LightPink',
    'Pink',
    'LightCoral',
]

listred =[
    'Crimson',
    'IndianRed',
    'Maroon',
    'DarkRed',
    'FireBrick',
    'Brown',
    'Salmon',
    'DarkSalmon',
    'LightSalmon',
    'Coral',
    'Tomato',
    'Red',
    'OrangeRed',
]

listorange =[
    'DarkOrange',
    'Orange',
]

listyellow =[
    'Gold',
    'Yellow',
    'Khaki',
]

listlight =[
    'White',
    'AliceBlue',
    'GhostWhite',
    'Snow',
    'Seashell',
    'FloralWhite',
    'WhiteSmoke',
    'Beige',
    'OldLace',
    'Ivory',
    'Linen',
    'Cornsilk',
    'AntiqueWhite',
    'BlanchedAlmond',
    'Bisque',
    'LightYellow',
    'LemonChiffon',
    'LightGoldenrodYellow',
    'PapayaWhip',
    'PeachPuff',
    'Moccasin',
    'PaleGoldenrod',
    'MistyRose',
    'LavenderBlush',
    'Lavender',
    'Thistle',
    'Azure',
    'LightCyan',
    'PowderBlue',
    'PaleTurquoise',
    'Honeydew',
    'MintCream',
]

listall =[
    listblack,
    listblue,
    listcyan,
    listgreen,
    listbrown,
    listpurple,
    listpink,
    listred,
    listorange,
    listyellow,
    listlight
]